// <auto-generated />
using System;
using MaterialMangement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaterialMangement.Migrations
{
    [DbContext(typeof(MaterialDbContext))]
    [Migration("20260609070135_AddStockRecord")]
    partial class AddStockRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("MaterialMangement.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specification")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "建材",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "水泥",
                            Quantity = 100m,
                            Remark = "普通硅酸盐水泥",
                            Specification = "P.O 42.5",
                            Unit = "吨",
                            UnitPrice = 450.00m
                        },
                        new
                        {
                            Id = 2,
                            Category = "建材",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "钢筋",
                            Quantity = 50m,
                            Remark = "热轧带肋钢筋",
                            Specification = "HRB400 Φ12",
                            Unit = "吨",
                            UnitPrice = 4200.00m
                        },
                        new
                        {
                            Id = 3,
                            Category = "建材",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "砂石",
                            Quantity = 200m,
                            Remark = "河砂",
                            Specification = "中砂",
                            Unit = "立方米",
                            UnitPrice = 85.00m
                        });
                });

            modelBuilder.Entity("MaterialMangement.Models.StockRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AfterQuantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BeforeQuantity")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Operation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Operator")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("StockRecords");
                });

            modelBuilder.Entity("MaterialMangement.Models.StockRecord", b =>
                {
                    b.HasOne("MaterialMangement.Models.Material", "Material")
                        .WithMany("StockRecords")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("MaterialMangement.Models.Material", b =>
                {
                    b.Navigation("StockRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
